consumer_token = "Your app's consumer token"
consumer_secret = "Your app's consumer secret"
access_key = "Your OAuth access key"
access_secret = "Your OAuth access secret"
firstUser = {}
firstUser['id'] = 20
firstUser['name'] = 'jack'
firstUser['followers'] = 2003219
firstUser['friends'] = 1172
